apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-game
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AARON40409/test-k8s-secret-game.git'
    targetRevision: k8s
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true