apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secret-game-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  # - host: aaron.com
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: secret-game-svc
            port:
              number: 80