# apiVersion: v1
# kind: Secret
# metadata:
#   name: secret-game-secret
# type: Opaque
# data:
#   DATABASE_URL: "cG9zdGdyZXNxbDovL2thdGlrYTpNRFl3TWpKak1qWXRNekV6TnkwME9HTXpMV0V4WW1FdE9EUmpZV1l3TmpFM05UVTVDZ0A1NC4zOC44MC4xNzM6NTQzNi9rYXRpa2FfZGI=" #"postgresql://katika:MDYwMjJjMjYtMzEzNy00OGMzLWExYmEtODRjYWYwNjE3NTU5Cg@54.38.80.173:5436/katika_db"
#   PORT: "NTg4MA=="
#   ACCESS_TOKEN_SECRET: "N0ZEM0E4RUM3RTlBMUIxRkVFREFGMEEyQjRDNTk=" #"7FD3A8EC7E9A1B1FEEDAF0A2B4C59"
#   ACCESS_TOKEN_EXPIRE: "MWQ="  #"1d"
#   REFRESH_TOKEN_SECRET: "OUM2QjIzRjFBOEQ0NzVFMkEwQjlDNDBFN0M5REE=" #"9C6B23F1A8D475E2A0B9C40E7C9DA"
#   REFRESH_TOKEN_EXPIRE: "N2Q="  #"7d"
  