apiVersion: v1
kind: Service
metadata:
  name: secret-game-svc
spec:
  selector:
    app: secret-game-api
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
