apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-game-cm
data:
  DATABASE_URL: "postgresql://katika:MDYwMjJjMjYtMzEzNy00OGMzLWExYmEtODRjYWYwNjE3NTU5Cg@54.38.80.173:5436/katika_db"
  PROD_ENV: "production"
